# ==========================================
# Namespace — greenops

apiVersion: v1
kind: Namespace
metadata:
  name: greenops
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: greenops
    greenops.io/env: base
